-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQghkJy+4yAumpHxmke
QbyjssrRufhGdNDebJQJCBUczFWgCgYIKoZIzj0DAQehRANCAARHYwGvWMhlfBYS
kroxLfCRlzk8bl5pXhJBtlt+UabSKADP6asWwxWS+Gd1nTRHL6rP3n+B8YcolIgB
PRggxDxf
-----END PRIVATE KEY-----